### ISSUE TITLE
sesskey error

### ISSUE THREAD

**Issue by Gardo32** [KenKout/bypass_seb_moodle#1]
```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\main.py", line 90, in <module>
    verify_configkey(url)
  File "C:\Users\User\Downloads\main.py", line 46, in verify_configkey
    sess_key = login.text.split('sesskey=')[1].split('"')[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of rang
```

**Comment by KenKout** [comment]
You need to change the url in the code into your school moodle
